openapi: 3.0.0
info:
  title: Real-Time File Editor
  description: API for Real-Time File Editor
  version: 1.0.0
  contact:
    name: Ogunba Joseph Adewole
    email: ogunbaja24@gmail.com
  license:
    name: Proprietary

servers:
  - url: https://realtimefileeditor.onrender.com
    description: Staging server
  - url: http://localhost:9091
    description: Local development server

